<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Rozumiem informacj o przetwarzaniu dan_0c6469</name>
   <tag></tag>
   <elementGuidId>17da1ea7-80c7-4fac-9bf0-3ecb265c1d7a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.wpcf7-list-item-label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='wpcf7-f58-o1']/form/div[2]/span/span/span/label/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wpcf7-list-item-label</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Rozumiem informację o przetwarzaniu danych osobowych oraz politykę prywatności serwisu.</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wpcf7-f58-o1&quot;)/form[@class=&quot;wpcf7-form&quot;]/div[@class=&quot;form-acceptamce&quot;]/span[@class=&quot;wpcf7-form-control-wrap acceptance-268&quot;]/span[@class=&quot;wpcf7-form-control wpcf7-acceptance&quot;]/span[@class=&quot;wpcf7-list-item&quot;]/label[1]/span[@class=&quot;wpcf7-list-item-label&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wpcf7-f58-o1']/form/div[2]/span/span/span/label/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='kontaktowy'])[1]/following::span[8]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Rozumiem']/parent::*</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/span</value>
   </webElementXpaths>
</WebElementEntity>
